// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ3lx9TgGU83_rMFxE01DuMgBQdB_jd5w',
    appId: '1:846361757603:web:7c45af60d56626122dfc16',
    messagingSenderId: '846361757603',
    projectId: 'flutter-mvvm-d9005',
    authDomain: 'flutter-mvvm-d9005.firebaseapp.com',
    storageBucket: 'flutter-mvvm-d9005.appspot.com',
    measurementId: 'G-4RGNCQVHNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAZl4vIEovLcfSFyxMuXkBPBceeuCgg-8',
    appId: '1:846361757603:android:4abe65d4c79aa1f02dfc16',
    messagingSenderId: '846361757603',
    projectId: 'flutter-mvvm-d9005',
    storageBucket: 'flutter-mvvm-d9005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHitd-n1bEDzRw4FOEqYyP1QAs_GC9uA',
    appId: '1:846361757603:ios:28e9fe48c7b483172dfc16',
    messagingSenderId: '846361757603',
    projectId: 'flutter-mvvm-d9005',
    storageBucket: 'flutter-mvvm-d9005.appspot.com',
    iosBundleId: 'com.example.flutterMvvm',
  );
}
